addons:
  firefox: latest
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
language: node_js
node_js:
  - '6.1'
notifications:
  slack:
    secure: B+WoTn0JfBWEdFZ8hKzXdYLc2W5cwngBrLoW9YM2jBFcXvidW8m/Aslq7koRw8F21R/sYlqtA1bYssmBBya4dLzGNZZA0+R8g0rwJwg5FjpJ/1DYfz7u5f/nhe5K2Wll7+4EPfuhN8LfK+38te6JBOc0xGBZdawTvFZkF2hBljFf2+YWutiUg9Vzmr/q51DffDCV9mziYGH+M30WBCTa9f+m7YNvAJxWzF3ckBLLhDUOj74P1a2bua2RICV3KZoVt2KeZ3VdERDk2xtRlqThJALJJzb/x8nkisb/DKWzuYzwrrtyT9IH/86tOz2rh/Dex26VH3piD76SqAl2VAjuS8TzIbKoXDxKLYyRNeAeLCNyiMT7049g5tTxug1sQ4uVAz97jH+sqP1CG3V67RhHRhC2zm6zKrU8biqoYLzFIKYUuYHHhek+2zizvYAzL5Z0z0+0VbtCd4zo5cL013jDvzzoFRmNKDMZqWjW52qYFrZDAccu5dNUuY7eXhnkQFC+Z1XY1WucBNyDg7O4iBTEy9RgkxapfCKqGPJKknArKD5YGp4xgnT/5g9mGQuRYtn86qzZVS76hKhSN15J9arjDRHNJYm/HVGRqWMFkCIolcrtRkyUFiiQgOMPCoNk7a2nPif0IgY5TqIxMojsF5jDoKzRT3JQ4TvJ6Ng7l5b6IDw=
